/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entity.Componente;
import entity.PMaestro;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import logic.ComponenteLogic;
import logic.NNetasLogic;
import logic.PMaestroLogic;
import logic.ModelRegistro;

/**
 *
 * @author Alexander Avila <alexanderavilab at gmail.com>
 */
public class Princ_RegistroInventario extends javax.swing.JFrame {

    /**
     * Creates new form Princ_RegistroInventario
     */
    
    private static int periodos;
    private static int componentes;
    
    public Princ_RegistroInventario() {
        initComponents();
        PanelRegistro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_comp = new javax.swing.JTextField();
        jText_Period = new javax.swing.JTextField();
        jButton_acept = new javax.swing.JButton();
        PanelRegistro = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        jTableInput = new javax.swing.JTable();
        jButton_sol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("MRP LOTE A LOTE");

        jLabel1.setText("Introduzca el Número de Componentes");

        jLabel2.setText("Introduzca el Número de  Periodos");

        jButton_acept.setText("ACEPTAR");
        jButton_acept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(167, 167, 167))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_Period, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_acept)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addComponent(jText_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jText_comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_Period, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_acept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Inventarios"));

        jTableInput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(jTableInput);

        jButton_sol.setText("GENERAR SOLUCIÓN");
        jButton_sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_solActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton_sol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_sol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetData(){
        
        ComponenteLogic.resetData();
        PMaestroLogic.resetData();
    }
    
    private void jButton_solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_solActionPerformed
        
        this.resetData();
        
        //GENERA PNN Y PNB
        PMaestro planM= new PMaestro();
        planM.setnPeriodos(this.periodos);
        planM.setnComponentes(this.componentes);
        
        for (int i = 0; i < this.componentes; i++) {
            
            Componente component = new Componente();
            component.setNombre((String)jTableInput.getValueAt(i, 0));
            component.setNivel(Integer.parseInt((String)jTableInput.getValueAt(i, 1)));
            component.setcPadre((String)jTableInput.getValueAt(i, 2));
            component.setTiempo_entrega(Integer.parseInt((String)jTableInput.getValueAt(i, 3)));
            component.setStock_disponible(Integer.parseInt((String)jTableInput.getValueAt(i, 4)));
            
            if(JOptionPane.showConfirmDialog(this, "¿Tiene Pedidos pendientes para el componente "+(i+1)+"?")==JOptionPane.OK_OPTION){
            
                Integer nPed = Integer.parseInt(
                               JOptionPane.showInputDialog(this, "Ingrese el número de pedidos pendientes para el componente", "1")
                               );
                
                List<Map<String,Integer>> lstPed_pendientes_recibir = new ArrayList<>();
                for (int j = 0; j < nPed; j++) {
                    
                    Integer pedido = Integer.parseInt(
                                 JOptionPane.showInputDialog(this, "Ingrese el Stock que recibirá", "1")
                                 );
                    
                    String periodo = JOptionPane.showInputDialog(this, "Ingrese el Periodo en el que recibirá el pedido", "1");
                    
                    Map<String, Integer> pedPendiente = new HashMap<>();
                    pedPendiente.put(periodo, pedido);
                
                    lstPed_pendientes_recibir.add(pedPendiente);
                }
                    component.setLstPed_pendientes_recibir(lstPed_pendientes_recibir);
            }
            
            ComponenteLogic.insertarComponente(component);
        }
        
        for (int i = 0; i < this.periodos; i++) {
            
          if(jTableInput.getValueAt(0, (i+5))!= null){
              
                PMaestro pMaestro = new PMaestro();
                Map<String, Integer> prod_requer = new HashMap<>();
                prod_requer.put(String.valueOf((i+1)) , 
                                Integer.parseInt((String)jTableInput.getValueAt(0, (i+5))));
               
                pMaestro.setCant_prod(prod_requer);
                PMaestroLogic.setProd_requer(pMaestro);
            }else{
              PMaestroLogic.setProd_requer(null);
            }
        
        }
        
        
        NNetasLogic.generarReporte(planM, ComponenteLogic.getLstComponentes());
    }//GEN-LAST:event_jButton_solActionPerformed

    private void jButton_aceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptActionPerformed
        
        
        this.periodos = Integer.parseInt(jText_Period.getText());
        this.componentes = Integer.parseInt(jText_comp.getText());
        
        PMaestro planMaster = new PMaestro();
        planMaster.setnComponentes(this.componentes);
        planMaster.setnPeriodos(this.periodos);
        PanelRegistro.setVisible(true);
        
        TableColumnModel columnModel = jTableInput.getColumnModel();
        //Set Modelo de la tabla
        jTableInput.setModel(ModelRegistro.modelRegistroInv(planMaster));
        ModelRegistro.setJComboTable(jTableInput, columnModel.getColumn(2));

        for (int i = 0; i < columnModel.getColumnCount(); i++) {
            columnModel.getColumn(i).setPreferredWidth(115);
        }
        
        jTableInput.setAutoResizeMode(jTableInput.AUTO_RESIZE_OFF);
    }//GEN-LAST:event_jButton_aceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Princ_RegistroInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Princ_RegistroInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Princ_RegistroInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Princ_RegistroInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Princ_RegistroInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton jButton_acept;
    private javax.swing.JButton jButton_sol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jTableInput;
    private javax.swing.JTextField jText_Period;
    private javax.swing.JTextField jText_comp;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
